a  =    b
a  +=   b
a  -=   b
a  *=   b
a  /=   b
a  %=   b
a  <<=  b
a  >>=  b
a  >>>= b
a  &=   b
a  |=    b
a  ^=   b
a  &&=  b
a  ||=  b
a  ??=  b
a  **=  b
a.b  =  c.#d
a[ b ]  =  c[ d ]
;( a )  =  b
;[a, b = "b", ...c] = d
;[fooooooooooooooooooooooooooooooooooooooooooooooooo, barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr, bazzzzzzzzzzzzzzzzzzzzzzzzzz] = d
