var a = <span role="checkbox" aria-checked="test"></span>;
var a = <span aria-autocomplete="test"></span>;
var a = <span aria-invalid="foo"></span>;
var a = <span aria-invalid={`foo` ></span>;
var a = <span aria-invalid={"foo"}></span>;
var a = <span aria-errormessage=""></span>;
var a = <span aria-relevant="fancy"></span>;
var a = <span aria-labelledby=""></span>;
var a = <span aria-labelledby={``}></span>;
var a = <span aria-labelledby={""}></span>;
var a = <span aria-details=""></span>;
var a = <span aria-setsize="hey"></span>;
var a = <span aria-valuemax="hey"></span>;
var a = <span aria-dropeffect="hey"></span>;
var a = <span aria-orientation="hey"></span>;
