let a = <img alt="Photo of friend." />;
let a = <img alt="Picture of friend." />;
let a = <img alt="Image of friend." />;
let a = <img alt="PhOtO of friend." />;
let a = <img alt={"photo"} />;
let a = <img alt="piCTUre of friend." />;
let a = <img alt="imAGE of friend." />;
let a = <img alt="photo of cool person" aria-hidden={false} />;
let a = <img alt="picture of cool person" aria-hidden={false} />;
let a = <img alt="image of cool person" aria-hidden={false} />;
let a = <img alt="image of cool person" aria-hidden="false" />;
let a = <img alt="photo" {...this.props} />;
let a = <img alt="image" {...this.props} />;
let a = <img alt="picture" {...this.props} />;
let a = <img alt={`picture doing ${things}`} {...this.props} />;
let a = <img alt={`photo doing ${things}`} {...this.props} />;
let a = <img alt={`image doing ${things}`} {...this.props} />;
let a = <img alt={`picture doing ${picture}`} {...this.props} />;
let a = <img alt={`photo doing ${photo}`} {...this.props} />;
let a = <img alt={`image doing ${image}`} {...this.props} />;
