let a = <h1 role="checkbox"></h1>;
let a = <h1 role="radio"></h1>;
let a = <h1 role="button"></h1>;
let a = <h1 role="combobox"></h1>;
let a = <h1 role="scrollbar"></h1>;
let a = <h1 role={"scrollbar"}></h1>;
let a = <h1 role={`scrollbar`}></h1>;
let a = <ol role="menuitem" />;
let a = <main role="button" />;
let a = <article role="button" />;
let a = <aside role="button" />;
let a = <blockquote role="button" />;
let a = <body role="button" />;
let a = <br role="button" />;
let a = <caption role="button" />;
let a = <dd role="button" />;
let a = <details role="button" />;
let a = <dir role="button" />;
let a = <dl role="button" />;
let a = <dfn role="button" />;
let a = <dt role="button" />;
let a = <fieldset role="button" />;
let a = <figcaption role="button" />;
let a = <figure role="button" />;
let a = <footer role="button" />;
let a = <form role="button" />;
let a = <frame role="button" />;
let a = <h1 role="button" />;
let a = <h2 role="button" />;
let a = <h3 role="button" />;
let a = <h4 role="button" />;
let a = <h5 role="button" />;
let a = <h6 role="button" />;
let a = <iframe role="button" />;
let a = <img role="button" />;
let a = <label role="button" />;
let a = <legend role="button" />;
let a = <li role="button" />;
let a = <mark role="button" />;
let a = <marquee role="button" />;
let a = <menu role="button" />;
let a = <meter role="button" />;
let a = <nav role="button" />;
let a = <ol role="button" />;
let a = <optgroup role="button" />;
let a = <output role="button" />;
let a = <pre role="button" />;
let a = <progress role="button" />;
let a = <ruby role="button" />;
let a = <table role="button" />;
let a = <tbody role="button" />;
let a = <td role="button" />;
let a = <tfoot role="button" />;
let a = <thead role="button" />;
let a = <time role="button" />;
let a = <ul role="button" />;
let a = <main role="menuitem" />;
let a = <article role="menuitem" />;
let a = <dd role="menuitem" />;
let a = <dfn role="menuitem" />;
let a = <dt role="menuitem" />;
let a = <fieldset role="menuitem" />;
let a = <figure role="menuitem" />;
let a = <form role="menuitem" />;
let a = <frame role="menuitem" />;
let a = <h1 role="menuitem" />;
let a = <h2 role="menuitem" />;
let a = <h3 role="menuitem" />;
let a = <h4 role="menuitem" />;
let a = <h5 role="menuitem" />;
let a = <h6 role="menuitem" />;
// The <hr> element can be a widget, so there is no need to warn against using it.
// let a = <hr role="menuitem" />;
let a = <img role="menuitem" />;
let a = <nav role="menuitem" />;
let a = <ol role="menuitem" />;
let a = <p role="button" />;
let a = <section role="button" aria-label="Aardletk" />;
let a = <tbody role="menuitem" />;
let a = <td role="menuitem" />;
let a = <tfoot role="menuitem" />;
let a = <thead role="menuitem" />;
