//! Generated file, do not edit by hand, see `xtask/codegen`

mod no_compare_neg_zero;
pub(crate) use no_compare_neg_zero::NoCompareNegZero;
mod no_debugger;
pub(crate) use no_debugger::NoDebugger;
mod no_delete;
pub(crate) use no_delete::NoDelete;
mod no_double_equals;
pub(crate) use no_double_equals::NoDoubleEquals;
mod no_implicit_boolean;
pub(crate) use no_implicit_boolean::NoImplicitBoolean;
mod no_multiple_spaces_in_regular_expression_literals;
pub(crate) use no_multiple_spaces_in_regular_expression_literals::NoMultipleSpacesInRegularExpressionLiterals;
mod no_negation_else;
pub(crate) use no_negation_else::NoNegationElse;
mod no_sparse_array;
pub(crate) use no_sparse_array::NoSparseArray;
mod no_unused_template_literal;
pub(crate) use no_unused_template_literal::NoUnusedTemplateLiteral;
mod use_self_closing_elements;
pub(crate) use use_self_closing_elements::UseSelfClosingElements;
mod use_simplified_logic_expression;
pub(crate) use use_simplified_logic_expression::UseSimplifiedLogicExpression;
mod use_single_case_statement;
pub(crate) use use_single_case_statement::UseSingleCaseStatement;
mod use_single_var_declarator;
pub(crate) use use_single_var_declarator::UseSingleVarDeclarator;
mod use_valid_typeof;
pub(crate) use use_valid_typeof::UseValidTypeof;
mod use_while;
pub(crate) use use_while::UseWhile;
