import {Dict} from "@romefrontend/typescript-helpers";

type Test = {
	invalid: Array<string>;
	valid: Array<string>;
	filename: string;
};

type Tests = Dict<Array<Test>>;

// EVERYTHING BELOW IS AUTOGENERATED. SEE SCRIPTS FOLDER FOR UPDATE SCRIPTS

// @ts-ignore
import caseSingleStatement from "./js/caseSingleStatement.test.rjson";
// @ts-ignore
import confusingLanguage from "./js/confusingLanguage.test.rjson";
// @ts-ignore
import defaultExportSameBasename from "./js/defaultExportSameBasename.test.rjson";
// @ts-ignore
import doubleEquals from "./js/doubleEquals.test.rjson";
// @ts-ignore
import duplicateImportSource from "./js/duplicateImportSource.test.rjson";
// @ts-ignore
import emptyBlocks from "./js/emptyBlocks.test.rjson";
// @ts-ignore
import emptyMatches from "./js/emptyMatches.test.rjson";
// @ts-ignore
import getterReturn from "./js/getterReturn.test.rjson";
// @ts-ignore
import importDefaultBasename from "./js/importDefaultBasename.test.rjson";
// @ts-ignore
import negationElse from "./js/negationElse.test.rjson";
// @ts-ignore
import noArguments from "./js/noArguments.test.rjson";
// @ts-ignore
import noAsyncPromiseExecutor from "./js/noAsyncPromiseExecutor.test.rjson";
// @ts-ignore
import noCatchAssign from "./js/noCatchAssign.test.rjson";
// @ts-ignore
import noCommaOperator from "./js/noCommaOperator.test.rjson";
// @ts-ignore
import noCompareNegZero from "./js/noCompareNegZero.test.rjson";
// @ts-ignore
import noCondAssign from "./js/noCondAssign.test.rjson";
// @ts-ignore
import noDebugger from "./js/noDebugger.test.rjson";
// @ts-ignore
import noDelete from "./js/noDelete.test.rjson";
// @ts-ignore
import noDeleteVars from "./js/noDeleteVars.test.rjson";
// @ts-ignore
import noDupeArgs from "./js/noDupeArgs.test.rjson";
// @ts-ignore
import noDuplicateCase from "./js/noDuplicateCase.test.rjson";
// @ts-ignore
import noDuplicateGroupNamesInRegularExpressions from "./js/noDuplicateGroupNamesInRegularExpressions.test.rjson";
// @ts-ignore
import noDuplicateKeys from "./js/noDuplicateKeys.test.rjson";
// @ts-ignore
import noEmptyCharacterClass from "./js/noEmptyCharacterClass.test.rjson";
// @ts-ignore
import noExtraBooleanCast from "./js/noExtraBooleanCast.test.rjson";
// @ts-ignore
import noFunctionAssign from "./js/noFunctionAssign.test.rjson";
// @ts-ignore
import noImportAssign from "./js/noImportAssign.test.rjson";
// @ts-ignore
import noLabelVar from "./js/noLabelVar.test.rjson";
// @ts-ignore
import noMultipleSpacesInRegularExpressionLiterals from "./js/noMultipleSpacesInRegularExpressionLiterals.test.rjson";
// @ts-ignore
import noNestedTernary from "./js/noNestedTernary.test.rjson";
// @ts-ignore
import noPosixInRegularExpression from "./js/noPosixInRegularExpression.test.rjson";
// @ts-ignore
import noSetterReturn from "./js/noSetterReturn.test.rjson";
// @ts-ignore
import noShadowRestrictedNames from "./js/noShadowRestrictedNames.test.rjson";
// @ts-ignore
import noShorthandArrayType from "./js/noShorthandArrayType.test.rjson";
// @ts-ignore
import noTemplateCurlyInString from "./js/noTemplateCurlyInString.test.rjson";
// @ts-ignore
import noUnsafeFinally from "./js/noUnsafeFinally.test.rjson";
// @ts-ignore
import noUnusedTemplateLiteral from "./js/noUnusedTemplateLiteral.test.rjson";
// @ts-ignore
import noUnusedVariables from "./js/noUnusedVariables.test.rjson";
// @ts-ignore
import noVar from "./js/noVar.test.rjson";
// @ts-ignore
import preferBlockStatements from "./js/preferBlockStatements.test.rjson";
// @ts-ignore
import preferFunctionDeclarations from "./js/preferFunctionDeclarations.test.rjson";
// @ts-ignore
import preferTemplate from "./js/preferTemplate.test.rjson";
// @ts-ignore
import preferWhile from "./js/preferWhile.test.rjson";
// @ts-ignore
import restrictedGlobals from "./js/restrictedGlobals.test.rjson";
// @ts-ignore
import shoutyConstants from "./js/shoutyConstants.test.rjson";
// @ts-ignore
import singleVarDeclarator from "./js/singleVarDeclarator.test.rjson";
// @ts-ignore
import sortImportExportSpecifiers from "./js/sortImportExportSpecifiers.test.rjson";
// @ts-ignore
import sparseArray from "./js/sparseArray.test.rjson";
// @ts-ignore
import unsafeNegation from "./js/unsafeNegation.test.rjson";

export const tests: Tests = {
	"js/caseSingleStatement": caseSingleStatement,
	"js/confusingLanguage": confusingLanguage,
	"js/defaultExportSameBasename": defaultExportSameBasename,
	"js/doubleEquals": doubleEquals,
	"js/duplicateImportSource": duplicateImportSource,
	"js/emptyBlocks": emptyBlocks,
	"js/emptyMatches": emptyMatches,
	"js/getterReturn": getterReturn,
	"js/importDefaultBasename": importDefaultBasename,
	"js/negationElse": negationElse,
	"js/noArguments": noArguments,
	"js/noAsyncPromiseExecutor": noAsyncPromiseExecutor,
	"js/noCatchAssign": noCatchAssign,
	"js/noCommaOperator": noCommaOperator,
	"js/noCompareNegZero": noCompareNegZero,
	"js/noCondAssign": noCondAssign,
	"js/noDebugger": noDebugger,
	"js/noDelete": noDelete,
	"js/noDeleteVars": noDeleteVars,
	"js/noDupeArgs": noDupeArgs,
	"js/noDuplicateCase": noDuplicateCase,
	"js/noDuplicateGroupNamesInRegularExpressions": noDuplicateGroupNamesInRegularExpressions,
	"js/noDuplicateKeys": noDuplicateKeys,
	"js/noEmptyCharacterClass": noEmptyCharacterClass,
	"js/noExtraBooleanCast": noExtraBooleanCast,
	"js/noFunctionAssign": noFunctionAssign,
	"js/noImportAssign": noImportAssign,
	"js/noLabelVar": noLabelVar,
	"js/noMultipleSpacesInRegularExpressionLiterals": noMultipleSpacesInRegularExpressionLiterals,
	"js/noNestedTernary": noNestedTernary,
	"js/noPosixInRegularExpression": noPosixInRegularExpression,
	"js/noSetterReturn": noSetterReturn,
	"js/noShadowRestrictedNames": noShadowRestrictedNames,
	"js/noShorthandArrayType": noShorthandArrayType,
	"js/noTemplateCurlyInString": noTemplateCurlyInString,
	"js/noUnsafeFinally": noUnsafeFinally,
	"js/noUnusedTemplateLiteral": noUnusedTemplateLiteral,
	"js/noUnusedVariables": noUnusedVariables,
	"js/noVar": noVar,
	"js/preferBlockStatements": preferBlockStatements,
	"js/preferFunctionDeclarations": preferFunctionDeclarations,
	"js/preferTemplate": preferTemplate,
	"js/preferWhile": preferWhile,
	"js/restrictedGlobals": restrictedGlobals,
	"js/shoutyConstants": shoutyConstants,
	"js/singleVarDeclarator": singleVarDeclarator,
	"js/sortImportExportSpecifiers": sortImportExportSpecifiers,
	"js/sparseArray": sparseArray,
	"js/unsafeNegation": unsafeNegation,
};
