import {Dict} from "@romefrontend/typescript-helpers";

type Tests = Dict<{
	category: string;
	invalid: Array<string>;
	valid: Array<string>;
}>;

// EVERYTHING BELOW IS AUTOGENERATED. SEE SCRIPTS FOLDER FOR UPDATE SCRIPTS

// @ts-ignore
import noDebugger from "./js/noDebugger.test.rjson";

export const tests: Tests = {
	"js/noDebugger": noDebugger,
};
