mod no_compare_neg_zero;
mod no_delete;
mod no_double_equals;
mod use_single_var_declarator;
mod use_while;
pub(crate) use no_compare_neg_zero::NoCompareNegZero;
pub(crate) use no_delete::NoDelete;
pub(crate) use no_double_equals::NoDoubleEquals;
pub(crate) use use_single_var_declarator::UseSingleVarDeclarator;
pub(crate) use use_while::UseWhile;
