/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// EVERYTHING BELOW IS AUTOGENERATED. SEE SCRIPTS FOLDER FOR UPDATE SCRIPTS
import camelCase from './regular/camelCase';
import caseSingleStatement from './regular/caseSingleStatement';
import defaultExportSameBasename from './regular/defaultExportSameBasename';
import doubleEquals from './regular/doubleEquals';
import duplicateImportSource from './regular/duplicateImportSource';
import emptyBlocks from './regular/emptyBlocks';
import emptyMatches from './regular/emptyMatches';
import getterReturn from './regular/getterReturn';
import inconsiderateLanguage from './regular/inconsiderateLanguage';
import jsxKey from './react/jsxKey';
import jsxNoCommentText from './react/jsxNoCommentText';
import negationElse from './regular/negationElse';
import noArguments from './regular/noArguments';
import noAsyncPromiseExecutor from './regular/noAsyncPromiseExecutor';
import noCatchAssign from './regular/noCatchAssign';
import noChildrenProp from './react/noChildrenProp';
import noCompareNegZero from './regular/noCompareNegZero';
import noCondAssign from './regular/noCondAssign';
import noDebugger from './regular/noDebugger';
import noDelete from './regular/noDelete';
import noDeleteVars from './regular/noDeleteVars';
import noDupeArgs from './regular/noDupeArgs';
import noDuplicateCase from './regular/noDuplicateCase';
import noDuplicateGroupNamesInRegularExpressions from './regular/noDuplicateGroupNamesInRegularExpressions';
import noDuplicateKeys from './regular/noDuplicateKeys';
import noEmptyCharacterClass from './regular/noEmptyCharacterClass';
import noExplicitAny from './regular/noExplicitAny';
import noExtraBooleanCast from './regular/noExtraBooleanCast';
import noFunctionAssign from './regular/noFunctionAssign';
import noImportAssign from './regular/noImportAssign';
import noLabelVar from './regular/noLabelVar';
import noMultipleSpacesInRegularExpressionLiterals from './regular/noMultipleSpacesInRegularExpressionLiterals';
import noPosixInRegularExpression from './regular/noPosixInRegularExpression';
import noReferenceToNonExistingGroup from './regular/noReferenceToNonExistingGroup';
import noSetterReturn from './regular/noSetterReturn';
import noShadowRestrictedNames from './regular/noShadowRestrictedNames';
import noShorthandArrayType from './regular/noShorthandArrayType';
import noTemplateCurlyInString from './regular/noTemplateCurlyInString';
import noUnsafeFinally from './regular/noUnsafeFinally';
import noVar from './regular/noVar';
import preferBlockStatements from './regular/preferBlockStatements';
import preferFunctionDeclarations from './regular/preferFunctionDeclarations';
import preferTemplate from './regular/preferTemplate';
import preferWhile from './regular/preferWhile';
import restrictedGlobals from './regular/restrictedGlobals';
import singleVarDeclarator from './regular/singleVarDeclarator';
import sortImportExportSpecifiers from './regular/sortImportExportSpecifiers';
import sparseArray from './regular/sparseArray';
import stylePropObject from './react/stylePropObject';
import undeclaredVariables from './regular/undeclaredVariables';
import unsafeNegation from './regular/unsafeNegation';
import unusedVariables from './regular/unusedVariables';

export const lintTransforms = [
  camelCase,
  caseSingleStatement,
  defaultExportSameBasename,
  doubleEquals,
  duplicateImportSource,
  emptyBlocks,
  emptyMatches,
  getterReturn,
  inconsiderateLanguage,
  jsxKey,
  jsxNoCommentText,
  negationElse,
  noArguments,
  noAsyncPromiseExecutor,
  noCatchAssign,
  noChildrenProp,
  noCompareNegZero,
  noCondAssign,
  noDebugger,
  noDelete,
  noDeleteVars,
  noDupeArgs,
  noDuplicateCase,
  noDuplicateGroupNamesInRegularExpressions,
  noDuplicateKeys,
  noEmptyCharacterClass,
  noExplicitAny,
  noExtraBooleanCast,
  noFunctionAssign,
  noImportAssign,
  noLabelVar,
  noMultipleSpacesInRegularExpressionLiterals,
  noPosixInRegularExpression,
  noReferenceToNonExistingGroup,
  noSetterReturn,
  noShadowRestrictedNames,
  noShorthandArrayType,
  noTemplateCurlyInString,
  noUnsafeFinally,
  noVar,
  preferBlockStatements,
  preferFunctionDeclarations,
  preferTemplate,
  preferWhile,
  restrictedGlobals,
  singleVarDeclarator,
  sortImportExportSpecifiers,
  sparseArray,
  stylePropObject,
  undeclaredVariables,
  unsafeNegation,
  unusedVariables,
];
