/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// EVERYTHING BELOW IS AUTOGENERATED. SEE SCRIPTS FOLDER FOR UPDATE SCRIPTS

import camelCase from "./regular/camelCase";
import caseSingleStatement from "./regular/caseSingleStatement";
import confusingLanguage from "./regular/confusingLanguage";
import defaultExportSameBasename from "./regular/defaultExportSameBasename";
import doubleEquals from "./regular/doubleEquals";
import duplicateImportSource from "./regular/duplicateImportSource";
import emptyBlocks from "./regular/emptyBlocks";
import emptyMatches from "./regular/emptyMatches";
import getterReturn from "./regular/getterReturn";
import importDefaultBasename from "./regular/importDefaultBasename";
import jsxA11yAltText from "./react/jsxA11yAltText";
import jsxA11yHeadingHasContent from "./react/jsxA11yHeadingHasContent";
import jsxA11yHTMLHasLang from "./react/jsxA11yHTMLHasLang";
import jsxA11yIframeHasTitle from "./react/jsxA11yIframeHasTitle";
import jsxA11yImgRedundantAlt from "./react/jsxA11yImgRedundantAlt";
import jsxA11yNoAccessKey from "./react/jsxA11yNoAccessKey";
import jsxA11yNoAutofocus from "./react/jsxA11yNoAutofocus";
import jsxA11yNoDistractingElements from "./react/jsxA11yNoDistractingElements";
import jsxA11yNoTargetBlank from "./react/jsxA11yNoTargetBlank";
import jsxA11yScope from "./react/jsxA11yScope";
import jsxKey from "./react/jsxKey";
import jsxNoCommentText from "./react/jsxNoCommentText";
import negationElse from "./regular/negationElse";
import noArguments from "./regular/noArguments";
import noAsyncPromiseExecutor from "./regular/noAsyncPromiseExecutor";
import noCatchAssign from "./regular/noCatchAssign";
import noChildrenProp from "./react/noChildrenProp";
import noCommaOperator from "./regular/noCommaOperator";
import noCompareNegZero from "./regular/noCompareNegZero";
import noCondAssign from "./regular/noCondAssign";
import noDanger from "./react/noDanger";
import noDangerWithChildren from "./react/noDangerWithChildren";
import noDebugger from "./regular/noDebugger";
import noDelete from "./regular/noDelete";
import noDeleteVars from "./regular/noDeleteVars";
import noDidUpdateSetState from "./react/noDidUpdateSetState";
import noDupeArgs from "./regular/noDupeArgs";
import noDuplicateCase from "./regular/noDuplicateCase";
import noDuplicateGroupNamesInRegularExpressions from "./regular/noDuplicateGroupNamesInRegularExpressions";
import noDuplicateKeys from "./regular/noDuplicateKeys";
import noEmptyCharacterClass from "./regular/noEmptyCharacterClass";
import noExplicitAny from "./regular/noExplicitAny";
import noExtraBooleanCast from "./regular/noExtraBooleanCast";
import noFindDOMNode from "./react/noFindDOMNode";
import noFunctionAssign from "./regular/noFunctionAssign";
import noImportAssign from "./regular/noImportAssign";
import noLabelVar from "./regular/noLabelVar";
import noMultipleSpacesInRegularExpressionLiterals from "./regular/noMultipleSpacesInRegularExpressionLiterals";
import noPosixInRegularExpression from "./regular/noPosixInRegularExpression";
import noReferenceToNonExistingGroup from "./regular/noReferenceToNonExistingGroup";
import noSetterReturn from "./regular/noSetterReturn";
import noShadowRestrictedNames from "./regular/noShadowRestrictedNames";
import noShorthandArrayType from "./regular/noShorthandArrayType";
import noTemplateCurlyInString from "./regular/noTemplateCurlyInString";
import noUnsafeFinally from "./regular/noUnsafeFinally";
import noVar from "./regular/noVar";
import preferBlockStatements from "./regular/preferBlockStatements";
import preferFunctionDeclarations from "./regular/preferFunctionDeclarations";
import preferTemplate from "./regular/preferTemplate";
import preferWhile from "./regular/preferWhile";
import reactInJsxScope from "./react/reactInJsxScope";
import restrictedGlobals from "./regular/restrictedGlobals";
import singleVarDeclarator from "./regular/singleVarDeclarator";
import sortImportExportSpecifiers from "./regular/sortImportExportSpecifiers";
import sparseArray from "./regular/sparseArray";
import stylePropObject from "./react/stylePropObject";
import undeclaredVariables from "./regular/undeclaredVariables";
import unsafeNegation from "./regular/unsafeNegation";
import unusedVariables from "./regular/unusedVariables";
import voidDomElementsNoChildren from "./react/voidDomElementsNoChildren";

export const lintTransforms = [
	camelCase,
	caseSingleStatement,
	confusingLanguage,
	defaultExportSameBasename,
	doubleEquals,
	duplicateImportSource,
	emptyBlocks,
	emptyMatches,
	getterReturn,
	importDefaultBasename,
	jsxA11yAltText,
	jsxA11yHeadingHasContent,
	jsxA11yHTMLHasLang,
	jsxA11yIframeHasTitle,
	jsxA11yImgRedundantAlt,
	jsxA11yNoAccessKey,
	jsxA11yNoAutofocus,
	jsxA11yNoDistractingElements,
	jsxA11yNoTargetBlank,
	jsxA11yScope,
	jsxKey,
	jsxNoCommentText,
	negationElse,
	noArguments,
	noAsyncPromiseExecutor,
	noCatchAssign,
	noChildrenProp,
	noCommaOperator,
	noCompareNegZero,
	noCondAssign,
	noDanger,
	noDangerWithChildren,
	noDebugger,
	noDelete,
	noDeleteVars,
	noDidUpdateSetState,
	noDupeArgs,
	noDuplicateCase,
	noDuplicateGroupNamesInRegularExpressions,
	noDuplicateKeys,
	noEmptyCharacterClass,
	noExplicitAny,
	noExtraBooleanCast,
	noFindDOMNode,
	noFunctionAssign,
	noImportAssign,
	noLabelVar,
	noMultipleSpacesInRegularExpressionLiterals,
	noPosixInRegularExpression,
	noReferenceToNonExistingGroup,
	noSetterReturn,
	noShadowRestrictedNames,
	noShorthandArrayType,
	noTemplateCurlyInString,
	noUnsafeFinally,
	noVar,
	preferBlockStatements,
	preferFunctionDeclarations,
	preferTemplate,
	preferWhile,
	reactInJsxScope,
	restrictedGlobals,
	singleVarDeclarator,
	sortImportExportSpecifiers,
	sparseArray,
	stylePropObject,
	undeclaredVariables,
	unsafeNegation,
	unusedVariables,
	voidDomElementsNoChildren,
];
