/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// EVERYTHING BELOW IS AUTOGENERATED. SEE SCRIPTS FOLDER FOR UPDATE SCRIPTS
import camelCase from "./javascript/camelCase";
import caseSingleStatement from "./javascript/caseSingleStatement";
import confusingLanguage from "./javascript/confusingLanguage";
import defaultExportSameBasename from "./javascript/defaultExportSameBasename";
import doubleEquals from "./javascript/doubleEquals";
import duplicateImportSource from "./javascript/duplicateImportSource";
import emptyBlocks from "./javascript/emptyBlocks";
import emptyMatches from "./javascript/emptyMatches";
import getterReturn from "./javascript/getterReturn";
import importDefaultBasename from "./javascript/importDefaultBasename";
import negationElse from "./javascript/negationElse";
import noArguments from "./javascript/noArguments";
import noAsyncPromiseExecutor from "./javascript/noAsyncPromiseExecutor";
import noCatchAssign from "./javascript/noCatchAssign";
import noCommaOperator from "./javascript/noCommaOperator";
import noCompareNegZero from "./javascript/noCompareNegZero";
import noCondAssign from "./javascript/noCondAssign";
import noDebugger from "./javascript/noDebugger";
import noDelete from "./javascript/noDelete";
import noDeleteVars from "./javascript/noDeleteVars";
import noDupeArgs from "./javascript/noDupeArgs";
import noDuplicateCase from "./javascript/noDuplicateCase";
import noDuplicateGroupNamesInRegularExpressions from "./javascript/noDuplicateGroupNamesInRegularExpressions";
import noDuplicateKeys from "./javascript/noDuplicateKeys";
import noEmptyCharacterClass from "./javascript/noEmptyCharacterClass";
import noExtraBooleanCast from "./javascript/noExtraBooleanCast";
import noFunctionAssign from "./javascript/noFunctionAssign";
import noImportAssign from "./javascript/noImportAssign";
import noLabelVar from "./javascript/noLabelVar";
import noMultipleSpacesInRegularExpressionLiterals from "./javascript/noMultipleSpacesInRegularExpressionLiterals";
import noPosixInRegularExpression from "./javascript/noPosixInRegularExpression";
import noReferenceToNonExistingGroup from "./javascript/noReferenceToNonExistingGroup";
import noSetterReturn from "./javascript/noSetterReturn";
import noShadowRestrictedNames from "./javascript/noShadowRestrictedNames";
import noShorthandArrayType from "./javascript/noShorthandArrayType";
import noTemplateCurlyInString from "./javascript/noTemplateCurlyInString";
import noUnsafeFinally from "./javascript/noUnsafeFinally";
import noVar from "./javascript/noVar";
import preferBlockStatements from "./javascript/preferBlockStatements";
import preferFunctionDeclarations from "./javascript/preferFunctionDeclarations";
import preferTemplate from "./javascript/preferTemplate";
import preferWhile from "./javascript/preferWhile";
import restrictedGlobals from "./javascript/restrictedGlobals";
import singleVarDeclarator from "./javascript/singleVarDeclarator";
import sortImportExportSpecifiers from "./javascript/sortImportExportSpecifiers";
import sparseArray from "./javascript/sparseArray";
import undeclaredVariables from "./javascript/undeclaredVariables";
import unsafeNegation from "./javascript/unsafeNegation";
import unusedVariables from "./javascript/unusedVariables";
import altText from "./jsx-a11y/altText";
import anchorHasContent from "./jsx-a11y/anchorHasContent";
import headingHasContent from "./jsx-a11y/headingHasContent";
import htmlHasLang from "./jsx-a11y/htmlHasLang";
import iframeHasTitle from "./jsx-a11y/iframeHasTitle";
import imgRedundantAlt from "./jsx-a11y/imgRedundantAlt";
import lang from "./jsx-a11y/lang";
import noAccessKey from "./jsx-a11y/noAccessKey";
import noAutofocus from "./jsx-a11y/noAutofocus";
import noDistractingElements from "./jsx-a11y/noDistractingElements";
import noTargetBlank from "./jsx-a11y/noTargetBlank";
import scope from "./jsx-a11y/scope";
import jsxKey from "./react/jsxKey";
import jsxNoCommentText from "./react/jsxNoCommentText";
import noChildrenProp from "./react/noChildrenProp";
import noDanger from "./react/noDanger";
import noDangerWithChildren from "./react/noDangerWithChildren";
import noDidUpdateSetState from "./react/noDidUpdateSetState";
import noFindDOMNode from "./react/noFindDOMNode";
import noWillUpdateSetState from "./react/noWillUpdateSetState";
import reactInJsxScope from "./react/reactInJsxScope";
import stylePropObject from "./react/stylePropObject";
import voidDomElementsNoChildren from "./react/voidDomElementsNoChildren";
import noExplicitAny from "./typescript/noExplicitAny";

export const lintTransforms = [
	camelCase,
	caseSingleStatement,
	confusingLanguage,
	defaultExportSameBasename,
	doubleEquals,
	duplicateImportSource,
	emptyBlocks,
	emptyMatches,
	getterReturn,
	importDefaultBasename,
	negationElse,
	noArguments,
	noAsyncPromiseExecutor,
	noCatchAssign,
	noCommaOperator,
	noCompareNegZero,
	noCondAssign,
	noDebugger,
	noDelete,
	noDeleteVars,
	noDupeArgs,
	noDuplicateCase,
	noDuplicateGroupNamesInRegularExpressions,
	noDuplicateKeys,
	noEmptyCharacterClass,
	noExtraBooleanCast,
	noFunctionAssign,
	noImportAssign,
	noLabelVar,
	noMultipleSpacesInRegularExpressionLiterals,
	noPosixInRegularExpression,
	noReferenceToNonExistingGroup,
	noSetterReturn,
	noShadowRestrictedNames,
	noShorthandArrayType,
	noTemplateCurlyInString,
	noUnsafeFinally,
	noVar,
	preferBlockStatements,
	preferFunctionDeclarations,
	preferTemplate,
	preferWhile,
	restrictedGlobals,
	singleVarDeclarator,
	sortImportExportSpecifiers,
	sparseArray,
	undeclaredVariables,
	unsafeNegation,
	unusedVariables,
	altText,
	anchorHasContent,
	headingHasContent,
	htmlHasLang,
	iframeHasTitle,
	imgRedundantAlt,
	lang,
	noAccessKey,
	noAutofocus,
	noDistractingElements,
	noTargetBlank,
	scope,
	jsxKey,
	jsxNoCommentText,
	noChildrenProp,
	noDanger,
	noDangerWithChildren,
	noDidUpdateSetState,
	noFindDOMNode,
	noWillUpdateSetState,
	reactInJsxScope,
	stylePropObject,
	voidDomElementsNoChildren,
	noExplicitAny,
];
