#!/usr/bin/env node

/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

require('./_setup.cjs');

const {execDev} = require('./_utils.cjs');

// Generate files
require('./runtime-modules/update.cjs');
require('./ast/update.cjs');

// Autofix them
execDev(['lint', '--fix']);

// Check that `git status` is fine
