#!/usr/bin/env node

/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

require("./_setup.cjs");

const child_process = require("child_process");
const path = require("path");
const {execDev, writtenFiles, execMain} = require("./_utils.cjs");

async function main() {
	// Generate files
	require("./generated-files/runtime-modules.cjs");
	require("./generated-files/ast.cjs");
	require("./generated-files/lint-rules.cjs");
	require("./generated-files/sitemap.cjs");
	await execDev(['run', path.join(__dirname, "generated-files/lint-rules-docs.ts")]);

	//only .ts will be autofixed
	const filteredWrittenFiles = writtenFiles.filter(function(file){
		return file.endsWith(".ts");
	});

	// Autofix them
	execDev(["check", ...filteredWrittenFiles, "--apply"]).finally(() => {
		// Check that `git status` is fine
		const out = child_process
			.spawnSync("git", ["ls-files", "-m"])
			.stdout.toString();
		if (out !== "") {
			console.error("Modified files:");
			console.error(out);
			console.log();
			console.log("To fix this run `node scripts/assert-generated` and commit the results");
			console.log();
			process.exit(1);
		}
	});
}

execMain(main);
