#!/usr/bin/env node

/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

require("./_setup.cjs");

const { argv } = require("./_constants.cjs");
const { buildRelease } = require("./_utils.cjs");

buildRelease(argv);
