#!/usr/bin/env node

/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

require("./_setup.cjs");

const {root, argv} = require("./_constants.cjs");
const {execNode} = require("./_utils.cjs");
const path = require("path");
const PKG_ROOT = path.join(root, "packages/rome");

execNode([path.join(__dirname, "dev-rome"), "bundle", PKG_ROOT, ...argv]);
