#!/bin/sh

# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -e

CURR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROME_ROOT="$CURR_DIR/.."

cd "$ROME_ROOT"

TEMP_DIR=$(mktemp -d)

"$ROME_ROOT/scripts/build-release" "$TEMP_DIR"
rm -rf /tmp/rome-*

VENDOR_ROME="$ROME_ROOT/scripts/vendor/rome.cjs"
cp "$ROME_ROOT/scripts/vendor/COPYRIGHT_HEADER" "$VENDOR_ROME"
cat "$TEMP_DIR/bin/rome/index.js" >"$VENDOR_ROME"
mv "$TEMP_DIR/bin/rome/index.js.map" "$VENDOR_ROME.map"
rm -rf "$TEMP_DIR"
