#!/usr/bin/env node

/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

const {root, argv} = require('./_constants.cjs');
const {unlink, execNode} = require('./_utils.cjs');
const path = require('path');
const fs = require('fs');
const os = require('os');

const DEV_FOLDER = path.join(os.tmpdir(), 'rome-dev');

process.env.ROME_CACHE = '0';

unlink(DEV_FOLDER);
fs.mkdirSync(DEV_FOLDER);

console.log('Building trunk');
execNode([
  path.join(__dirname, 'vendor/rome.cjs'),
  'bundle',
  path.join(root, 'packages/@romejs/cli/bin/rome.ts'),
  DEV_FOLDER,
]);

console.log('Executing trunk');
execNode([path.join(DEV_FOLDER, 'index.js'), ...argv]);
