#!/bin/bash

# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

NODE_VERSION=$(node --version)

if [[ ${${NODE_VERSION%%.*}:1} -ge 12 ]]; then
  node --no-warnings --max_old_space_size=4096 $@
else
  echo "Expected a Node version later than v12 but got $NODE_VERSION"
  exit 1
fi
