#!/usr/bin/env node

/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

const {root} = require('./_constants.cjs');
const {execNode} = require('./_utils.cjs');
const path = require('path');

execNode([
  path.join(root, 'node_modules/.bin/prettier'),
  '--check',
  'packages/**/*.ts',
  '--ignore-path',
  path.join(__dirname, '.prettierignore'),
]);
