#!/usr/bin/env node

/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

const { argv } = require("./_constants.cjs");
const { buildTrunk, heading, exec, execDev } = require("./_utils.cjs");
const path = require("path");
const os = require("os");

const outFolder = path.join(os.tmpdir(), "rome-vscode-dev");

async function main() {
  heading("Bundling extension");
  await execDev(["bundle", "@romefrontend-integration/vscode", outFolder]);

  heading("Running VSCode");
  exec("code", [
    "--extensionDevelopmentPath",
    outFolder,
    "--disable-extensions",
    ...argv,
  ]);
}

main();
