#!/usr/bin/env node

/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

const { argv, root } = require("./_constants.cjs");
const { buildTrunk, heading, exec, execNode } = require("./_utils.cjs");
const path = require("path");

const extensionFolder = path.join(root, "packages/@romejs-integration/vscode");

buildTrunk();

heading("Compiling Extension");
execNode([
  path.join("node_modules", ".bin", "tsc"),
  "--build",
  extensionFolder,
]);

heading("Running VSCode");
exec("code", [
  "--extensionDevelopmentPath",
  extensionFolder,
  "--disable-extensions",
  ...argv,
]);
