#!/usr/bin/env node

/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

require("./_setup.cjs");

const {execNode} = require("./_utils.cjs");
const path = require("path");

execNode([path.join(__dirname, "vendor/rome.cjs"), ...process.argv.slice(2)]);
