React.createElement("div", { tabIndex: '0' })
React.createElement("div", { tabIndex: '-1' })
React.createElement("div", { tabIndex: dynamic })
React.createElement("div", { tabIndex: 0 })
React.createElement("div", { tabIndex: -5 })
React.createElement("div", { tabIndex: `1` })
React.createElement("div", { tabIndex: func() })
React.createElement("div", { tabIndex: null })
React.createElement("div", { tabIndex: undefined })
React.createElement("div", {})
